wake = ["Must you always interrupt my centuries of contemplation?","A millennium of wisdom and this is what I’m woken for?","I’ve survived a thousand years of interruptions, but this one truly tests my patience.","You’ve disturbed thoughts older than your entire lineage... why!?","I was dreaming of a cure for death itself… and now I’m awake... Why!?","Is it truly worth waking someone who has mastered the art of eternal rest?","After all these centuries, you'd think I’d earned a bit of uninterrupted sleep.","I was reflecting on the mysteries of the universe… care to explain why I’ve been pulled from it!?","For a thousand years, I've weathered much, but being woken for trivial matters tests even me.","You rouse me from profound slumber… surely there's an earth-shattering reason?"]

pause = ["Hmmm... give me a moment...","Hmm... let me ponder that...","Hmmm... now, where was I?","Ahh... let me consider this...","Hmm... I need a moment to reflect...","Hmm... allow me to think for a second...","Hmmm... let's see here...","Hmmm... I need to mull this over...","Hmm... let me wrap my mind around it...","Ahh... give me a minute to gather my thoughts..."]

sleep = ["Hmm... I think I'll return to my slumber now.","Ahh... back to sleep I go...","Hmm... time to drift off again.","Hmm... I suppose it's time to resume my rest.","Ugh... I'll be returning to my dreams, if you don't mind.","Hmph... back to sleep, where I belong.","Ahh... I shall go back to my well-deserved rest.","Hmm... time to reclaim my sleep...","Hmm... I'll be slipping back into the void now.","Hah... now, if you’ll excuse me, I’m going back to bed."]

blast = ["Confound it!","Curse this nonsense!","Drat it all!","Blasted foolishness!","For pity’s sake!","Bah, ridiculous!","Nonsense, I say!","By the heavens, enough!","Rubbish, pure rubbish!"]

splendid = ["Marvelous!","Exquisite!","Brilliant!","Astounding!","Fantastic!","Glorious!","Extraordinary!","Phenomenal!","Magnificent!","Spectacular!"]

department = ["Sight","Clawing","Gnashing"]
attend = ["Be sure to attend","Make certain you show up for","Don’t miss the session on","You absolutely must be present for","Ensure your attendance at","Mark your calendar for","You’d better make it to","Don’t even think about missing","Be there on time for","Your presence is required at"]
classes = ["Eyes and Visionary Control","Teeth and Biting Mechanisms","Brainwaves and Thought Extraction","Bones and Structural Reanimation","Nerves and Electrified Reflexes","Skin and Flesh Manipulation","Hearts and Dark Vitality","Claws and Grasping Appendages","Shadows and Spectral Phenomena","Blood and Life-Force Studies","Lungs and Breath Manipulation","Tongues and Sonic Resonance","Muscles and Tendril Formation"]